set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports G]
set_property IOSTANDARD LVCMOS33 [get_ports HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports R]
set_property IOSTANDARD LVCMOS33 [get_ports VSYNC]
set_property PACKAGE_PIN T15 [get_ports R]
set_property PACKAGE_PIN R16 [get_ports G]
set_property PACKAGE_PIN U17 [get_ports B]
set_property PACKAGE_PIN V13 [get_ports VSYNC]
set_property PACKAGE_PIN V15 [get_ports HSYNC]

set_property PACKAGE_PIN M20 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property DRIVE 12 [get_ports B]