set_property PACKAGE_PIN U17 [get_ports R_out]
set_property PACKAGE_PIN R16 [get_ports G_out]
set_property PACKAGE_PIN T15 [get_ports B_out]
set_property PACKAGE_PIN V15 [get_ports Hsync_out]
set_property PACKAGE_PIN V13 [get_ports Vsync_out]
set_property IOSTANDARD LVCMOS33 [get_ports B_out]
set_property IOSTANDARD LVCMOS33 [get_ports G_out]
set_property IOSTANDARD LVCMOS33 [get_ports Hsync_out]
set_property IOSTANDARD LVCMOS33 [get_ports R_out]
set_property IOSTANDARD LVCMOS33 [get_ports Vsync_out]

set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports G]
set_property IOSTANDARD LVCMOS33 [get_ports HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports R]
set_property IOSTANDARD LVCMOS33 [get_ports VSYNC]
set_property PACKAGE_PIN T15 [get_ports R]
set_property PACKAGE_PIN R16 [get_ports G]
set_property PACKAGE_PIN U17 [get_ports B]
set_property PACKAGE_PIN V13 [get_ports VSYNC]
set_property PACKAGE_PIN V15 [get_ports HSYNC]

set_property PACKAGE_PIN M20 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property DRIVE 12 [get_ports B]

set_property PACKAGE_PIN D20 [get_ports btn1]
set_property PACKAGE_PIN L20 [get_ports btn2]
set_property PACKAGE_PIN L19 [get_ports btn3]
set_property IOSTANDARD LVCMOS33 [get_ports btn1]
set_property IOSTANDARD LVCMOS33 [get_ports btn2]
set_property IOSTANDARD LVCMOS33 [get_ports btn3]

