# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ShiftRegTest_0_0/design_1_ShiftRegTest_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ShiftRegTest_0_0 || ORIG_REF_NAME==design_1_ShiftRegTest_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/lscho/OneDrive/Documents/GitHub/mo6-digitaal-scherm/ShiftRegTest/ShiftRegTest.gen/sources_1/bd/design_1/design_1_ooc.xdc
